#!/bin/bash

status="$(playerctl status 2>/dev/null)"
if [ "$status" = "Playing" ]; then
  icon=""
elif [ "$status" = "Paused" ]; then 
  icon=""
else
  echo ""
  exit
fi

title=`exec playerctl metadata xesam:title`
artist=`exec playerctl metadata xesam:artist`
echo "$icon   $title - $artist"
